### ISSUE TITLE
Output of test run prints in spork terminal, not in caller.

### ISSUE THREAD

**Issue by briandunn** [sporkrb/spork-testunit#1]
For other spork clients, running a test causes the output to be displayed in the caller terminal.
The output of testdrb is printed in the terminal where spork was started.

Test output should be routed to the caller's terminal.

**Comment by timcharper** [comment]
Sorry, I need to redeploy the gem.  The latest version in master should fix this issue

**Comment by briandunn** [comment]
Right you are. Thanks! One more bit of weirdness, though:
    .....
    Finished in 1.066776 seconds.

```
#<DRb::DRbUnknown:0x12ef350>
```

Any Idea what that last object coming though might be?

**Comment by jeremyw** [comment]
Hey Tim, can you push 0.0.2 to gemcutter?

**Comment by timcharper** [comment]
Hey Jeremy, I'm trying to, but I don't appear to have access.  I'll see what I need to do to claim the gem... :S

**Comment by timcharper** [comment]
I emailed Nick Quaranto of the gemcutter team. He assigned it over to me, and I pushed 0.0.2.  Thanks for the feedback!

**Comment by cswilliams** [comment]
I'm experiencing the same weirdness as brian.  For example, running testdrb in my terminal works perfectly:
    >testdrb test/unit/customer_test.rb
    Loaded suite customer_test.rb
    Started
    .....
    Finished in 4.544192 seconds.
    5 tests, 7 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

Yet, if I do the following:
    >testdrb test/unit/customer_test.rb  > output.txt
    > cat output.txt
    Loaded suite customer_test.rb
    Started
    .....
    Finished in 4.537602 seconds.

```
#<DRb::DRbUnknown:0x1017d08a0>
```

You also can get this identical strange output if you just run the testdrb command in textmate from a system() call or equivalent.
I was sort of able to fix it in textmate by wrapping my call to testdrb in a PTY.spawn block, but the output still isn't quite right...
