### ISSUE TITLE
Exception encountered: #<LoadError: no such file to load -- test/unit/autorunner>

### ISSUE THREAD

**Issue by Dagnan** [sporkrb/spork-testunit#13]
Hi.

This is the error I'm getting when I want to launch a test through testdrb or buncle exec testdrb.
I use Rails 3 with Ruby 1.9.2. I know that the support of Ruby 1.9 is recent but it seems to work perfectly in other users environment :/

**Comment by fidel** [comment]
I've also encountered this problem today...

**Comment by dburrows** [comment]
Not sure if this will fix the exact problem you were having but adding the test directory to the path (using the -I switch) when running testdrb solved most of my load errors, run your test from your rails root like so:

@testdrb -I test test/unit/mymodel_test.rb@

**Comment by Dagnan** [comment]
Not happening with newer versions of spork and spork-testunit.
