### ISSUE TITLE
Missing framework error

### ISSUE THREAD

**Issue by sreid99** [sporkrb/spork-testunit#16]
I installed the gems as per :

```
gem 'spork', '~> 0.9.0.rc', :group => [:development, :test]
gem 'spork-testunit', :group => [:development, :test]
```

then modified my test_helper.rb as per your wiki page.

Then I tried to run spork (from within the project root folder) as :

```
spork testunit --bootstrap (also tried without --bootstrap)
```

I get the error

```
"Couldn't find a supported test framework that begins with 'testunit' ..."
```

I'm using rails3 on windows.

**Comment by adie** [comment]
Try run it with bundler:

```
bundle exec spork
```

**Comment by sreid99** [comment]
That worked. 

I can now run the tests, but get :
`uninitialised constant Capistrano`
I ran the tests using “testdrb -Itest *_/_.rb" which I found on the web. (I also tried using bundle exec in front)

I don't get this running the tests normally (without spork). Also capistrano is not included in my test environment, but it looks like bundler is trying to load it when running the tests under spork. 

Am I using the wrong command to run the tests ? What is the correct way to run tests under spork where I previously used e.g. rake test:units ?

**Comment by sreid99** [comment]
I've found I can run most unit tests ok with the following command line :
`testdrb -I test test/unit/*.rb`
However, one test (which passes with `rake test:units`) still fails. Is it possible the above command line does not run the rails initializers ?
