### ISSUE TITLE
testdrb -Itest test/**/*_test.rb not working

### ISSUE THREAD

**Issue by Dagnan** [sporkrb/spork-testunit#21]
Hi.

When I try testdrb -Itest test/*_/__test.rb, only files in test/unit are launched ("Running tests with args" gives me the list).
Files in other test/ subdirectories are missing.

Out of curiosity I also tried testdrb -Itest test/**/**/__test.r, which gives me test/functionnal/_, test/integration/_, test/unit/helpers/_ but not test/unit/*.

**Comment by timcharper** [comment]
Can you try and figure out how to code it up to make it do what you want? I don't use the gem, so difficult for me to do this. so am looking for a maintainer / pull requests.

**Comment by Dagnan** [comment]
Actually lib/tasks/spork.rake already contains this line

```
run "testdrb -Itest test/unit/* test/functional/**/* test/integration/**/*"
```

that does the job. Altough it mixes up the tests so I prefer to use:

```
run "testdrb -Itest test/unit/*"
run "testdrb -Itest test/functional/**/*"
run "testdrb -Itest test/integration/**/*"
```
