### ISSUE TITLE
Doesn't reload code

### ISSUE THREAD

**Issue by jackkinsella** [sporkrb/spork-testunit#22]
I set up spork and my test helper as per the Wiki and I started it up. I ran the testdrb command on an integration test and it passes as expected. Then I modify a method in a controller to raise an error. Running the test again does not give a failure. 

Starting up spork again shows the failure. If I fix it, while spork is still running, it does not pick up the fix.

Using Capybara, Ruby 1.9, Rails 3.1 and Spork-testunit

<pre><code>
require 'rubygems'
require 'spork'

Spork.prefork do 
  ENV["RAILS_ENV"] = "test"
  require File.expand_path('../../config/environment', __FILE__)
  require 'rails/test_help'

  #get capybara working
  require 'capybara/rails'
  class ::ActionDispatch::IntegrationTest
    include Capybara::DSL
  end

end

class ActiveSupport::TestCase
  # Add more helper methods to be used by all tests here...
end
</code></pre>

**Comment by rojotek** [comment]
Anyone got any insights into this?

I'm seeing the same.  It feels like I might need to put something into the Spork.each_run block, but I don't know what.
