### ISSUE TITLE
How do I run the entire test suite?

### ISSUE THREAD

**Issue by abelmartin** [sporkrb/spork-testunit#37]
Hi there,

Before, I used to simply type `rake` and my entire suite would run.  Now I find that I have to type `testdrb -I test test/unit/* test/functional/* test/functional/*/* test/integration/*`.  I have to add the `test/functional/*/*` because I have nested resources.

Now, I could alias this to make my life easier, but is there a way to run my entire suite easily that I'm not seeing?

-a

**Comment by aspiers** [comment]
I'd like to know this too!

**Comment by ruprict** [comment]
This works for me:

find . -name *_test.rb | xargs testdrb -Itest 

Obviously won't work on windows, and it may not be ideal, but it works....

**Comment by abelmartin** [comment]
Nice @ruprict. I figured I'd be doing some chicanery like this and setting an alias.  I've since changed my test suite from Test::Unit to RSpec.  There are just too many nice tools for RSpec that I can no longer ignore, one of which is vanilla spork :)
