### ISSUE TITLE
"wrong argument type DRb::DRbObject" when using ruby-debug

### ISSUE THREAD

**Issue by wkrsz** [sporkrb/spork-testunit#7]
When I try to use ruby-debug I get the following error in client (testdrb) process:

```
INTERNAL ERROR!!! wrong argument type DRb::DRbObject (expected File)
```

Spork server outputs no errors and keeps on running happily.

Here's full output: http://pastie.org/1501703

**Comment by timcharper** [comment]
Did you load "spork/ext/ruby-debug" ?

**Comment by wkrsz** [comment]
That was it. I wasn't aware of spork/ext/ruby-debug. Thanks for lightning fast reply - you rock!
